name: CEE6501_jupyter
channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - ipykernel
  - jupyterlab
  - numpy
  - scipy
  - pandas
  - matplotlib
  - notebook
  - jupyterlab_rise # going from jupyter lab to presentation
  # - seaborn     # for prettier plots (optional)
  # - scikit-learn  # for machine learning demos (optional)
  # - sympy       # for symbolic math (optional)
